blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion or Questions
    url: https://github.com/Budsyoda/LeadTap/discussions
    about: Use Discussions for broader product input, use cases, or random ideas.
